system:
  env: dev
  addr: 8888
  db-type: mysql
  oss-type: local
local:
  path: uploads/file
  store-path: uploads/file
mysql:
  host: 127.0.0.1
  port: 3306
  database: blog
  username: root
  password: root
  charset: utf8mb4
  prefix: ""
  max_idle_conns: 10
  max_open_conns: 100
  max_lifetime: 3600s
redis:
  host: 127.0.0.1
  port: 6379
  password:
  database: 0
logger:
  level: info
  prefix: '[gin-jj]'
  format: console
  director: log
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  max-age: 0
  show-line: true
  log-in-console: true
dindin:
  access_token: 
  secret: 